package com.ignorant.carrentalsystem.model;

import java.util.*;

public record Branch(String name, Set<VehicleType> supportedVehicleTypes) {

    public Branch(String name, List<VehicleType> supportedTypesInput) {
        this( // Call the canonical constructor generated by the record
                Objects.requireNonNull(name, "Branch name cannot be null"),
                Set.copyOf(Objects.requireNonNull(
                        supportedTypesInput, "Supported types cannot be null"))
        );
        if (name.isBlank()) {
            throw new IllegalArgumentException("Branch name cannot be blank");
        }
    }

//    public Branch(String name, List<VehicleType> supportedVehicleTypes){
//        this(
//                Objects.requireNonNull(name, "Branch name can not be null"),
//        Collections.unmodifiableCollection(new HashSet<>(
//                Objects.requireNonNull(supportedVehicleTypes, "Supported types cannot be null")
//        ))
//        );
//
//        if (name.isBlank()){
//            throw new IllegalArgumentException("Branch name can not be blank");
//        }
//    }
}
